# Generated by Django 4.2.1 on 2023-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Name')),
                ('Category', models.CharField(blank=True, choices=[('Phones', 'Phones'), ('Gadgets', 'Gadgets')], default='', max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
