# Generated by Django 4.2.1 on 2023-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='Comments',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
