# Generated by Django 4.2.1 on 2023-05-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0004_inventory_type_inventory_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='Return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
