# Generated by Django 4.2.1 on 2023-05-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0006_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Category',
            field=models.CharField(blank=True, choices=[('Phones', 'Phones'), ('Gadgets', 'Gadgets')], default='', max_length=50),
        ),
    ]
