# Generated by Django 4.2.1 on 2023-05-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0007_alter_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Category',
            field=models.CharField(blank=True, choices=[('Phones', 'Phones'), ('Gadgets', 'Gadgets')], default='', max_length=50, null=True),
        ),
    ]
