# Generated by Django 4.2.1 on 2023-05-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0008_alter_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='Return',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Warehouse',
        ),
    ]
