# Generated by Django 4.2.1 on 2023-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0009_remove_inventory_return_remove_inventory_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('Vendor', models.CharField(blank=True, default='', max_length=120, null=True)),
            ],
        ),
    ]
