# Generated by Django 4.2.1 on 2023-05-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0010_samp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Samp',
        ),
    ]
