# Generated by Django 4.2.1 on 2023-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp24', '0012_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('Type', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], default='', max_length=50, null=True)),
                ('Category', models.CharField(blank=True, choices=[('Phones', 'Phones'), ('Gadgets', 'Gadgets')], default='', max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, default='', null=True)),
                ('Vendor', models.CharField(blank=True, choices=[('China', 'China'), ('Dubai', 'Dubai')], default='', max_length=120, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
